# config

model: {
  framework: "tensorflow",
  save_dir: "./outputs",
  weight: "../../models/tensorflow/tensorflow_cnn/cnn.pb",
  graph: "",
  inputs: [
    {
      name: "x",
      shape: [ 1, 28, 28, 1 ],
      layout: "NHWC",
      pixel_format: "GRAY",
      mean: [ 104.0 ],
      std: [ 1.0 ],
      resize_type: 0,
      padding_value: 128,
      padding_mode: 0,
      data_path: "/DEngine/tyexamples/data/datasets/ILSVRC2012/ILSVRC2012_img_val/ILSVRC2012_val_00000001.JPEG",
    }
  ],

  outputs: [
    {
      name: "fc2/output",  # TensorFlow必须设置
    }
  ],
}

build: {
  target: "nnp300",
  enable_quant: true,
  enable_build: true,
  quant: {
    data_dir: "/DEngine/tyexamples/data/datasets/ILSVRC2012/ILSVRC2012_img_val",
    prof_img_num: 50,
    similarity_img_num: 1,
    similarity_dataset: ,
    custom_preprocess_module: ,
    custom_preprocess_cls: ,
    debug_level: 0,
    calib_method: "kld",
    skip_layer_idxes: [ ],
    skip_layer_types: [ ],
  },
  enable_dump: 1,
}
