# config

model: {
  framework: "caffe",
  save_dir: "./outputs",
  weight: "../../models/caffe/caffe_multi_input_model/multi_input_case.caffemodel",
  graph: "../../models/caffe/caffe_multi_input_model/multi_input_case_deploy.prototxt",
  inputs: [
    {
      name: "input0",
      shape: [ 1, 3, 112, 112 ],
      layout: "NCHW",
      pixel_format: "BGR",
      mean: [ 127.5, 127.5, 127.5 ],
      std: [ 127.5, 127.5, 127.5 ],
      resize_type: 0,
      padding_value: 128,
      padding_mode: 0,
      data_path: "../../data/datasets/ILSVRC2012/ILSVRC2012_img_val/ILSVRC2012_val_00000001.JPEG",
    },
    {
      name: "input1",
      shape: [ 1, 3, 224, 224 ],
      layout: "NCHW",
      pixel_format: "RGB",
      mean: [ 127.5, 127.5, 127.5 ],
      std: [ 127.5, 127.5, 127.5 ],
      resize_type: 0,
      padding_value: 128,
      padding_mode: 0,
      data_path: "../../data/datasets/ILSVRC2012/ILSVRC2012_img_val/ILSVRC2012_val_00000001.JPEG",
    }
  ],

  outputs: [ ],
}

build: {
  target: "nnp300",
  enable_quant: true,
  enable_build: true,
  quant: {
    data_dir: "../../data/datasets/ILSVRC2012/ILSVRC2012_img_val",
    prof_img_num: 50,
    similarity_img_num: 1,
    similarity_dataset: ,
    custom_preprocess_module: "custom_preprocess",
    custom_preprocess_cls: "CustomMultiInputModel",
    debug_level: -1,
    calib_method: "kld",
    skip_layer_idxes: [ ],
    skip_layer_types: [ ],
  },
  enable_dump: 0
}
