# config

model: {
  framework: "tensorflow",
  save_dir: "./outputs",
  weight: "../../models/tensorflow/tensorflow_imgD/imgD.pb",
  graph: ,
  inputs: [
    {
      name: "Placeholder",
      shape: [ 1, 544, 960, 4 ],
      layout: "NHWC",
      pixel_format: "None",
      mean: [ 0, 0, 0, 0 ] ,
      std: [ 1, 1, 1, 1 ],
      resize_type: 0,
      padding_value: 128,
      padding_mode: 0,
      data_path: "../../data/pic/rgbd/rgb/banana.png",
    }
  ],

  outputs: [
    {
      name: "sid_unet/u0_layer/transition_layer/BiasAdd",  # TensorFlow必须设置
    }
  ],
}

build: {
  target: "nnp300",
  enable_quant: true,
  enable_build: true,
  quant: {
    data_dir: "../../data/pic/rgbd",
    prof_img_num: 50,
    similarity_img_num: 1,
    similarity_dataset: ,
    custom_preprocess_module: "custom_preprocess",
    custom_preprocess_cls: "CustomTensorFlowImgD",
    debug_level: 0,
    calib_method: "kld",
    skip_layer_idxes: [ 3, 131 ],
    skip_layer_types: [ ],
  },
  enable_dump: 1,
}



