# config

model: {
  framework: "onnx",
  save_dir: "./dp2000",
  weight: "../../models/onnx/onnx_squeezenet_v1.1/squeezenet1.1-7.onnx",
  graph: "",
  inputs: [
    {
      name: "data",
      shape: [ 1, 3, 227, 227 ],
      layout: "NCHW",
      pixel_format: "RGB",
      mean: [ 104.0, 117.0, 123.0 ],
      std: [ 1.0, 1.0, 1.0 ],
      resize_type: 0,
      padding_value: 128,
      padding_mode: 0,
      data_path: "/DEngine/tyexamples/data/datasets/ILSVRC2012/ILSVRC2012_img_val/ILSVRC2012_val_00000001.JPEG",
    }
  ],

  outputs: [ ],

  model_impl_module: "model_impl",
  model_impl_cls: "SqueezeNetV1_1"
}

build: {
  target: "nnp300",
  enable_quant: true,
  enable_build: true,
  enable_dump: 1,
  quant: {
    data_dir: "/DEngine/tyexamples/data/datasets/ILSVRC2012/ILSVRC2012_img_val",
    prof_img_num: 50,
    similarity_img_num: 1,
    similarity_dataset: ,
    custom_preprocess_module: ,
    custom_preprocess_cls: ,
    debug_level: 0,
    calib_method: "kld",
    skip_layer_idxes: [ ],
    skip_layer_types: [ ],
  },
}

test: {
  data_dir: "/DEngine/tyexamples/data/datasets/ILSVRC2012/ILSVRC2012_img_val",
  test_num: 20,
  dataset_module: "dataset",
  dataset_cls: "Dataset",
}

demo: {
  data_dir: "/DEngine/tyexamples/data/datasets/ILSVRC2012/ILSVRC2012_img_val",
  num: 10,
}
