# config

model: {
  framework: "caffe",
  save_dir: "./outputs",
  weight: "../../models/caffe/caffe_centernet_dla34/invasion_dla34.caffemodel",
  graph: "../../models/caffe/caffe_centernet_dla34/caffe_centernet_dla34_part2.prototxt",
  inputs: [
    {
      name: "cat_blob11_input",
      shape: [ 1, 128, 128, 128 ],
      layout: "NCHW",
      pixel_format: "None",
      mean: ,
      std: ,
      resize_type: 0,
      padding_value: 128,
      padding_mode: 0,
      data_path: ,
    },
    {
      name: "relu_blob47_input",
      shape: [ 1, 64, 64, 64 ],
      layout: "NCHW",
      pixel_format: "None",
      mean: ,
      std: ,
      resize_type: 0,
      padding_value: 128,
      padding_mode: 0,
      data_path: ,
    }
  ],

  outputs: [],
}

build: {
  target: "nnp300",
  enable_quant: true,
  enable_build: true,
  quant: {
    data_dir: "",
    prof_img_num: 50,
    similarity_img_num: 1,
    similarity_dataset: ,
    custom_preprocess_module: "custom_preprocess",
    custom_preprocess_cls: "CustomCenterNetDLA34Part2",
    debug_level: 0,
    calib_method: "kld",
    skip_layer_idxes: [ ],
    skip_layer_types: [ ],
  },
  enable_dump: 1
}
