# 模型量化编译配置文件

model: {
  # 模型名字, 若存在自定义预处理python脚本名字必须与model_name一致，必须与yml文件名字一致
  name: "tensorflow_imgD",

  # 模型框架，必须设置
  framework: "tensorflow",

  # 量化文件以及各种过程文件保存路径
  save_dir: "/DEngine/tyexamples/models/dp2000_1",

  # 模型权重路径，必须设置
  weight: "/DEngine/tyexamples/models/tensorflow/tensorflow_imgD/imgD.pb",

  # 模型图结构定义路径，非caffe/mxnet框架模型可以不设置
  graph: ,

  # 模型输入配置，存在多个输入，注意顺序
  # 目前不能分别设置多个输入的NHWC->NCHW的转换, 必须相同
  inputs: [
    {
      name: "Placeholder",  # 输入名称
      shape: [ 1, 544, 960, 4 ], # 原模型的实际输入形状
      layout: "NHWC",  # 输入数据布局，支持 NCHW，NHWC
      pixel_format: "None",  # 像素格式，支持 None(未知), RGB，BGR，GRAY
      mean: ,   # 输入均值，支持broadcast；不配置，默认使用0
      std: ,   # 输入方差，支持broadcast；不配置，默认使用1
      resize_type: 0,   # resize类型，0-长宽分别resize，1-长边等比例resize，2-短边等比例resize，默认为0
      padding_value: 128,  # resize图像不足部分将自动padding，默认128
      padding_mode: 0,  # 目前仅支持 0: 左上角(LEFT_TOP), 1: 中心点(CENTER), 默认0，仅等比例resize生效
      # 用于比较各阶段输出的相似度，空表示采用随机数
      img_path: "/DEngine/tyexamples/data/pic/rgbd/rgb/banana.png",
    }
  ],

  # 存在多个输出，注意顺序
  # 目前不能分别设置多输出的NHWC->NCHW的转换, 必须相同
  outputs: [
    {
      name: "sid_unet/u0_layer/transition_layer/BiasAdd",  # TensorFlow必须设置
    }
  ],
}

config: {
  # 目标平台，必须设置
  target: "nnp300",

  # 是否跳过量化编译过程，仅做CPU端的浮点和定点仿真，默认为true
  # 注意disable之前必须已经生成量化模型
  enable_quant: true,

  # 量化配置参数，仅在enable_quant为true生效
  quant: {
    # 量化输入数据路径(必须设置)
    data_dir: "/DEngine/tyexamples/data/pic/rgbd",

    # 量化使用的数据数量，0表示使用所有数据，默认为0
    prof_img_num: 50,

    # 进行check_similarity的图片的张数，默认为1。如果大于1，最终会输出所有图片的平均相似度；如果等于0，则会处理similarity_dataset中所有图片
    similarity_img_num: 1,

    # 进行相似度比对的输入数据，配置为空，则默认取前述dataset接口表示的输入。具体配置参照dataset，可定义为图片集路径，或用户自定义的预处理。
    similarity_dataset: ,

    # 用户自定义量化函数，若不配置此项，则使用默认前处理，多输入或非1,3通道数据必须配置
    custom_preprocess: "CustomTensorFlowImgD",

    # 量化调试等级, 默认为1
    # 0 - 输出整体余弦相似度,
    # 1 - 输出整体余弦相似度、输出逐层余弦相似度、逐层保存浮点模型和定点模型的数据、逐层保存浮点定点的对比PNG图
    # 2 - 输出整体余弦相似度、输出逐层余弦相似度、逐层保存浮点定点的对比PNG图
    # 3 - 输出整体余弦相似度、输出逐层余弦相似度
    #-1 - 不输出debug信息
    debug_level: 0,

    # 校准方法 "kld", "min_max", "percentile_0.99..", "l2norm", 可以缺省此项，默认kld
    calib_method: "kld",

    # 可配置为 op 的索引，可单个配置也可组成 list, 可以缺省此项
    skip_layer_idxes: [ 3, 131 ],

    # 可配置为op的类型，可单个配置也可组成 list, 可以为空list或缺省此项
    skip_layer_types: [ ],   # 例子 ["nn.conv2d", "nn.conv2d"]
  },

  # 是否使能进行逐层dump结果，默认为0
  enable_dump: 0,
}



