# config

model: {
  framework: "onnx",
  save_dir: "./outputs",
  weight: "../../models/onnx/onnx_resnet50/resnet50.onnx",
  graph: "",
  inputs: [
    {
      name: "data",
      shape: [ 8, 3, 224, 224 ],
      layout: "NCHW",
      pixel_format: "RGB",
      mean: [ 123.675, 116.28, 103.53 ],
      std: [ 58.395, 57.12, 57.375 ],
      resize_type: 0,
      padding_value: 128,
      padding_mode: 0,
      data_path: "../../data/datasets/ILSVRC2012/ILSVRC2012_img_val/ILSVRC2012_val_00000001.JPEG",
    }
  ],

  outputs: [ ],

  model_impl_module: "model_impl",
  model_impl_cls: "ResNet50"
}

build: {
  target: "nnp400",
  enable_quant: true,
  enable_build: true,
  quant: {
    data_dir: "../../data/datasets/ILSVRC2012/ILSVRC2012_img_val",
    prof_img_num: 100,
    similarity_img_num: 1,
    similarity_dataset: ,
    custom_preprocess_module: ,
    custom_preprocess_cls: ,
    debug_level: 0,
    calib_method: "l2norm",
  },
  enable_dump: 2,
}

test: {
  data_dir: "../../data/datasets/ILSVRC2012/ILSVRC2012_img_val",
  test_num: 0,
  dataset_module: "dataset",
  dataset_cls: "Dataset",
}

demo: {
  data_dir: "../../data/datasets/ILSVRC2012/ILSVRC2012_img_val",
  num: 20,
}
