# config file

model: {
  framework: "onnx",
  name: ,
  save_dir: "./outputs",
  weight: "yolov5s_surgeon.onnx",
  graph: "",
  inputs: [
    {
      name: "images",
      shape: [ 1, 3, 640, 640 ],
      layout: "NCHW",
      pixel_format: "RGB",
      mean: [ 0, 0, 0 ],
      std: [ 255.0, 255.0, 255.0 ],
      resize_type: 1,
      padding_value: 114,
      padding_mode: 1,
      data_path: "../../data/datasets/ILSVRC2012/ILSVRC2012_img_val/ILSVRC2012_val_00000002.JPEG",
    }
  ],

  outputs: [],

  model_impl_module: "model_impl",
  model_impl_cls: "YoloV5s",

  custom_op_module: "detection_out",
}

build: {
  target: "nnp400",
  enable_quant: true,
  enable_build: true,
  opt_level: 0,
  quant: {
    data_dir: "../../data/datasets/ILSVRC2012/ILSVRC2012_img_val",
    prof_img_num: 50,
    similarity_img_num: 1,
    similarity_dataset: ,
    custom_preprocess_module: ,
    custom_preprocess_cls: ,
    debug_level: -1,
    calib_method: "l2norm",
    skip_layer_names: [ "final" ],
  },
  enable_dump: 2,
}

test: {
  data_dir: "../../data/datasets/coco_val2017/val2017",
  test_num: 0,
  dataset_module: "dataset",
  dataset_cls: "Dataset",
}

demo: {
  data_dir: "../../data/datasets/coco_val2017/val2017",
  num: 20,
}
